# Semantic Matching  

## Preliminary Operations

In [9]:
import pandas as pd
import numpy as np
import faiss
import openai
from openai import OpenAI
from sklearn.metrics import f1_score, accuracy_score, precision_score, confusion_matrix
import re

In [3]:
#pd.set_option('display.width', 1000) 
#pd.set_option('display.max_colwidth', None)
#pd.set_option('display.max_rows', None)

In [4]:
client = OpenAI(api_key="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")

In [27]:
df_kb = pd.read_csv(r'df_kb_generation.csv')
df_test = pd.read_csv(r'df_test_generation.csv', nrows=20)

In [6]:
unique_label_counts = df_test['label'].value_counts()
print(unique_label_counts)

label
true        599
false       388
mixture     201
unproven     45
Name: count, dtype: int64


In [7]:
unique_label_counts = df_kb['label'].value_counts()
print(unique_label_counts)

label
True    5078
Name: count, dtype: int64


In [28]:
#Clean text
# Rimuovi le parti precedenti a :\r\n
df_test['new_claim'] = df_test['new_claim'].apply(lambda x: re.sub(r'.*:\r\n', '', x)) 
df_test['new_expl'] = df_test['new_expl'].apply(lambda x: re.sub(r'.*:\r\n', '', x))

In [29]:
#Clean text
#Rimuovi altri parti
df_test['new_claim'] = df_test['new_claim'].replace('"""\r\n', '', regex=True) 
df_test['new_claim'] = df_test['new_claim'].replace('\r\n"""', '', regex=True)
df_test['new_expl'] = df_test['new_expl'].replace('"""\r\n', '', regex=True) 
df_test['new_expl'] = df_test['new_expl'].replace('\r\n"""', '', regex=True)

In [30]:
#Clean text
# Rimuovi le parti precedenti a :\r\n
df_kb['new_claim'] = df_kb['new_claim'].apply(lambda x: re.sub(r'.*:\r\n', '', x)) 
df_kb['new_expl'] = df_kb['new_expl'].apply(lambda x: re.sub(r'.*:\r\n', '', x))

In [31]:
#Clean text
#Rimuovi altri parti
df_kb['new_claim'] = df_kb['new_claim'].replace('"""\r\n', '', regex=True) 
df_kb['new_claim'] = df_kb['new_claim'].replace('\r\n"""', '', regex=True)
df_kb['new_expl'] = df_kb['new_expl'].replace('"""\r\n', '', regex=True) 
df_kb['new_expl'] = df_kb['new_expl'].replace('\r\n"""', '', regex=True)

In [ ]:
df_kb[['new_claim','new_expl']]

In [ ]:
df_test[['new_claim','new_expl']]

### Matching New Claim

In [15]:
claims = df_kb["new_claim"].tolist()
len(claims)

5078

In [16]:
def get_embedding(input, model="text-embedding-3-small", encoding_format = "float"):
  obj = client.embeddings.create(
    model=model,
    input=input,
    encoding_format=encoding_format
  )
  return obj.data[0].embedding

In [17]:
import pickle
with open("embeddings_claims.pkl", "rb") as f:
    vectors_claim = pickle.load(f)

In [18]:
vectors_claim.shape[1]

1536

In [19]:
np.arange(len(claims))

array([   0,    1,    2, ..., 5075, 5076, 5077])

In [20]:
index = faiss.IndexIDMap(faiss.IndexFlatIP(vectors_claim.shape[1]))
faiss.normalize_L2(vectors_claim)
index.add_with_ids(vectors_claim, np.arange(len(claims)))

In [21]:
def index_search(query, k=1):
    query_vector =get_embedding(query)
    query_vector = np.array(query_vector, dtype=np.float32).reshape(1, -1)
    faiss.normalize_L2(query_vector)
    top_k = index.search(query_vector, k)
    
    return(top_k[0], [
        claims[_id] for _id in top_k[1][0]
    ])

In [22]:
index_search('Cigarette cause cancer', k=3)

(array([[0.59109044, 0.5069936 , 0.47763616]], dtype=float32),
 ['Tobacco has been reported to cause 2.4 million cases of cancer in the United States.',
  '"The presence of nicotine in cigarette butts poses a serious health risk to babies and small children."',
  'Quit smoking is strongly recommended by experts and tobacco companies to reduce the risk of COVID-19.'])

In [49]:
def verify_claim(claim, k=3, thresholds=[0.5, 0.7, 0.9]):
    # Ottieni i risultati della ricerca FAISS per la nuova affermazione
    similarity_scores, matched_claims = index_search(claim, k=k)
    
    # La similarità massima trovata tra la nuova affermazione e le corrispondenze
    max_similarity = np.max(similarity_scores) if similarity_scores.size > 0 else 0
    
    # Determina se l'affermazione è vera secondo le soglie di similarità
    verdicts = {}
    for threshold in thresholds:
        verdicts[threshold] = "True" if max_similarity >= threshold else "False"
    
    return verdicts, max_similarity, matched_claims

In [50]:
# Esempio di utilizzo della funzione
claim = 'Cigarette cause cancer'
verdicts, max_similarity, matched_claims = verify_claim(claim, k=3)

print(f"Verdicts: {verdicts}")
print(f"Max Similarity: {max_similarity}")
print("Matched Claims:")
for claim in matched_claims:
    print(f"- {claim}")

Verdicts: {0.5: 'True', 0.7: 'False', 0.9: 'False'}
Max Similarity: 0.5910904407501221
Matched Claims:
- Tobacco has been reported to cause 2.4 million cases of cancer in the United States.
- "The presence of nicotine in cigarette butts poses a serious health risk to babies and small children."
- Quit smoking is strongly recommended by experts and tobacco companies to reduce the risk of COVID-19.


In [51]:
def get_binary_verdict_and_print(row, threshold=0.5):
    claim = row['new_claim']
    true_label = row['label']  # Assume che la colonna con le label si chiami 'label'
    _, max_similarity, matched_claims = verify_claim(claim, k=3)
    is_true = max_similarity >= threshold

    print(f"Claim: {claim}")
    print(f"True Label: {true_label}")
    print(f"Verdict at threshold {threshold}: {'True' if is_true else 'False'}")
    print("Matched Claims from Knowledge Base:")
    for matched_claim in matched_claims:
        print(f"- {matched_claim}")
    print(f"Max Similarity: {max_similarity}\n")
    
    return is_true

In [52]:
# Applica la funzione apply_verify_and_get_binary_verdict a ogni new_claim nel DataFrame
df_test['predicted_label'] = df_test.apply(get_binary_verdict_and_print, threshold=0.5, axis=1)

true_labels = df_test['label'].apply(lambda x: 'true' if x == 'true' else 'false')
true_labels = true_labels.map({'true': 1, 'false': 0})
#predicted_labels = df_test['predicted_label'].fillna('false') # Sostituisce NaN con 'false'
predicted_labels = df_test['predicted_label'].map({True: 1, False: 0})  

# Calcolo delle metriche
f1 = f1_score(true_labels, predicted_labels)
accuracy = accuracy_score(true_labels, predicted_labels)
precision = precision_score(true_labels, predicted_labels, zero_division=0)

print(f"F1-Score: {f1}")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")

cm_a = confusion_matrix(true_labels, predicted_labels)
    
tn_a, fp_a, fn_a, tp_a = cm_a.ravel()

print(f"\nMetodo 'a' - Matrice di Confusione:")
print(f"TN: {tn_a}, FP: {fp_a}, FN: {fn_a}, TP: {tp_a}")

Claim: "The mother, in a letter to her child after her death, disclosed that she only had one eye because she had given her other eye to him."
True Label: false
Verdict at threshold 0.5: False
Matched Claims from Knowledge Base:
- The daughter expressed her true feelings towards her late mother through a harsh and critical obituary.
- "The experience of miscarriages deeply influences the artwork of a mom-to-be, reflecting her emotional journey in a powerful way."
- "The mother's call for changes at Salem Hospital follows the tragic death of her baby."
Max Similarity: 0.48532429337501526

Claim: "Research indicates that a significant number of Americans continue to consume alcohol excessively."
True Label: true
Verdict at threshold 0.5: False
Matched Claims from Knowledge Base:
- Europeans, as reported by the WHO, have been identified as the heaviest drinkers globally.
- Based on the data, it is indicated that a significant percentage of American adults have engaged in activities that c

### Matching New Explanation

In [53]:
explanation = df_kb["new_expl"].tolist()
len(explanation)

5078

In [59]:
def get_embedding(input, model="text-embedding-3-small", encoding_format = "float"):
  obj = client.embeddings.create(
    model=model,
    input=input,
    encoding_format=encoding_format
  )
  return obj.data[0].embedding

In [61]:
with open("embeddings_explaination.pkl", "rb") as f:
    vectors_expl = pickle.load(f)

In [62]:
vectors_expl.shape[1]

1536

In [63]:
np.arange(len(claims))

array([   0,    1,    2, ..., 5075, 5076, 5077])

In [64]:
index = faiss.IndexIDMap(faiss.IndexFlatIP(vectors_expl.shape[1]))
faiss.normalize_L2(vectors_expl)
index.add_with_ids(vectors_expl, np.arange(len(explanation)))

In [66]:
def index_search(query, k=1):
    query_vector =get_embedding(query)
    query_vector = np.array(query_vector, dtype=np.float32).reshape(1, -1)
    faiss.normalize_L2(query_vector)
    top_k = index.search(query_vector, k)
    
    return(top_k[0], [
        explanation[_id] for _id in top_k[1][0]
    ])

In [78]:
def verify_new_expl(claim, k=3, thresholds=[0.5, 0.7, 0.9]):
    # Ottieni i risultati della ricerca FAISS per la nuova affermazione
    similarity_scores, matched_claims = index_search(claim, k=k)
    
    # La similarità massima trovata tra la nuova affermazione e le corrispondenze
    max_similarity = np.max(similarity_scores) if similarity_scores.size > 0 else 0
    
    # Determina se l'affermazione è vera secondo le soglie di similarità
    verdicts = {}
    for threshold in thresholds:
        verdicts[threshold] = "True" if max_similarity >= threshold else "False"
    
    return verdicts, max_similarity, matched_claims

In [77]:
index_search('Tobacco cause cancer', k=3)

(array([[0.5762931 , 0.5081805 , 0.49784362]], dtype=float32),
 ['The Centers for Disease Control and Prevention reported that tobacco use led to 2.4 million cancer cases in the United States between 1999 and 2004.',
  'By tripling the tobacco tax worldwide, smoking rates could decrease by a third, leading to the prevention of 200 million premature deaths caused by diseases like lung cancer throughout this century.',
  'The statement highlights the devastating impact of tobacco on American lives, surpassing the death toll of World War II, AIDS, cocaine, heroin, alcohol, vehicular accidents, homicide, and suicide combined.'])

In [79]:
def get_binary_verdict_and_print(row, threshold=0.5):
    new_expl = row['new_expl']
    true_label = row['label']  # Assume che la colonna con le label si chiami 'label'
    _, max_similarity, matched_new_expls = verify_new_expl(new_expl, k=3)
    is_true = max_similarity >= threshold

    print(f"Explanation: {new_expl}")
    print(f"True Label: {true_label}")
    print(f"Verdict at threshold {threshold}: {'True' if is_true else 'False'}")
    print("Matched new_expls from Knowledge Base:")
    for matched_new_expl in matched_new_expls:
        print(f"- {matched_new_expl}")
    print(f"Max Similarity: {max_similarity}\n")
    
    return is_true

In [80]:
# Applica la funzione apply_verify_and_get_binary_verdict a ogni new_claim nel DataFrame
df_test['predicted_label'] = df_test.apply(get_binary_verdict_and_print, threshold=0.5, axis=1)

true_labels = df_test['label'].apply(lambda x: 'true' if x == 'true' else 'false')
true_labels = true_labels.map({'true': 1, 'false': 0})
#predicted_labels = df_test['predicted_label'].fillna('false') # Sostituisce NaN con 'false'
predicted_labels = df_test['predicted_label'].map({True: 1, False: 0})  

# Calcolo delle metriche
f1 = f1_score(true_labels, predicted_labels)
accuracy = accuracy_score(true_labels, predicted_labels)
precision = precision_score(true_labels, predicted_labels, zero_division=0)

print(f"F1-Score: {f1}")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")

cm_a = confusion_matrix(true_labels, predicted_labels)
    
tn_a, fp_a, fn_a, tp_a = cm_a.ravel()

print(f"\nMetodo 'a' - Matrice di Confusione:")
print(f"TN: {tn_a}, FP: {fp_a}, FN: {fn_a}, TP: {tp_a}")

Explanation: The story of the one-eyed mother emphasizes the profound love that mothers have for their children and the importance of appreciating their sacrifices while they are still alive.
True Label: false
Verdict at threshold 0.5: False
Matched new_expls from Knowledge Base:
- The daughter wrote a harsh and critical obituary to express her negative feelings towards her deceased mother.
- The emotional turmoil of experiencing miscarriages influences the art of mom-to-be, Ashley MacLure, depicting fairies, young girls on giant moths, and anguished, bleeding women in her creations.
- The survivors of Japan's tsunami continue to endure silent suffering, like Hatsuko Ishikawa who tragically lost her 36-year-old son, a firefighter, to the devastating waves three years ago.
Max Similarity: 0.4025361239910126

Explanation: According to a study, a significant number of Americans exceed the recommended alcohol intake, with 18% of men and 11% of women drinking more than advised. Additionally

KeyboardInterrupt: 